### ISSUE TITLE
T75.- Requisito funcional: Trabajar información de los egresados y  carga de datos de los egresados

### ISSUE THREAD

**Issue by DittUnamba** [DittUnamba/Ditt-PILAR#41]
Se proporcionaron 24 archivos .xls  12 de egresados y 12 de graduados hasta el 2021, de los cuales se debe hacer un cruce para solo sacar aquellos egresados los cuales no tienen título, ademas se debe serciorarse que es estos egresados no se repitan omo estuidantes de la misma carrera, pasarlo al formato de la tabla matrics, luego importar a la base de datos.

**Comment by SSegundoGonzales** [comment]
Se realizó la importación de 3896 de los cuales 912 son estudiantes y en ciclo se considera 0 como indicador de egresado, ademas se recomienda hacer el cruce con la información de titulados actualizada que proporcionara grados y título.
